services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_trading_development
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/crypto_trading_development
      REDIS_URL: redis://redis:6379/1
      GOOGLE_CLIENT_ID: 428959067055-qfbpbcsvd1sgnld4jd0lf1pq3ghgcr7d.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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

  vite:
    build: .
    command: yarn dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - web

  css:
    build: .
    command: yarn watch:css
    volumes:
      - .:/app
    depends_on:
      - web

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      #- node_modules:/app/node_modules
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/crypto_trading_development
      REDIS_URL: redis://redis:6379/1

volumes:
  db-data:
  redis-data:
  bundle:
  node_modules: