version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_trading_development
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/crypto_trading_development
      REDIS_URL: redis://redis:6379/1

  js:
    build: .
    command: yarn watch
    volumes:
      - .:/app
    depends_on:
      - web

  css:
    build: .
    command: yarn watch:tailwind
    volumes:
      - .:/app
    depends_on:
      - web

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/crypto_trading_development
      REDIS_URL: redis://redis:6379/1

volumes:
  db-data:
  redis-data: